apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vivekics/argocd-demos.git    # Replace it with your forked repo
    targetRevision: main
    path: declarative_approach/online_shop
  destination:
    server: app_of_apps/apps/online_shop_app.yml   # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: stackforge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
